baseURL = 'https://tuehkea.netlify.app/'
languageCode = 'en-us'
title = 'Tue Hellstern :: Kea'
theme = 'hugo-book'

# Book configuration
disablePathToLower = true
enableGitInfo = true

[params]
BookToC = true
BookSection = '*'
BookComments = false
